import type { EstimatorResponse } from './types';

// Pre-baked demo response for the Apex code review bot use case.
// Grounded in: 53 Apex classes, 3 LWC, 5 Aura, 21 users (Accenture dev org).
// Numbers are internally consistent: cost Lowest < Balanced < Fastest; time Fastest < Balanced < Lowest.
export const DEMO_RESPONSE: EstimatorResponse = {
  options: [
    {
      optionLabel: 'Lowest cost',
      optimizedFor: 'Minimal tooling spend, leveraging existing SF licences',
      tradeoff: 'Slower delivery; uses free/included tools only where possible',
      title: 'Apex Quality Gate — Lean',
      summary: 'Delivers a working code review bot using GitHub Actions and Einstein Code already in the Salesforce stack. Longer runway but lowest ongoing spend given the existing Aura/Apex footprint.',
      complexity: 'Medium',
      totalManualDays: 45,
      totalAiDays: 29,
      totalManualCost: 32400,
      totalAiCost: 7800,
      monthlyRunCost: 175,
      deployTimeWeeks: 9,
      aiTimeSavingPct: 36,
      banner: 'AI cuts 16 delivery days and reduces tooling cost to $175/mo by maximising existing Salesforce licences.',
      tasks: [
        {
          phase: 'Requirements',
          task: 'Define Apex quality rules & thresholds',
          description: 'Catalogue coding standards, security rules, and quality gates for 53-class codebase',
          aiTool: 'Claude',
          aiToolCategory: 'Requirements',
          manualDays: 4,
          aiDays: 2,
          toolMonthlyCost: 0,
          confidence: 'High',
          rationale: 'Claude generates a draft ruleset from Apex best-practice docs in hours vs days',
        },
        {
          phase: 'Design',
          task: 'Architect GitHub Actions + Copado integration',
          description: 'Design pipeline that triggers on PR, runs analysis, blocks on threshold breach',
          aiTool: 'GitHub Copilot',
          aiToolCategory: 'Code Gen',
          manualDays: 5,
          aiDays: 3,
          toolMonthlyCost: 19,
          confidence: 'High',
          rationale: 'Copilot accelerates YAML pipeline and webhook config authoring',
        },
        {
          phase: 'Development',
          task: 'Build Apex static analysis engine',
          description: 'Custom PMD/Checkmarx rules + LWC parser integrated with existing 53 Apex classes',
          aiTool: 'Einstein Code',
          aiToolCategory: 'Code Gen',
          manualDays: 16,
          aiDays: 11,
          toolMonthlyCost: 0,
          confidence: 'Medium',
          rationale: 'Already licensed — set to $0. Einstein Code understands existing Apex patterns, reducing boilerplate by ~35%',
        },
        {
          phase: 'Testing / QA',
          task: 'Regression suite against existing Apex classes',
          description: 'Validate bot does not flag false positives across all 53 existing classes',
          aiTool: 'Copado AI',
          aiToolCategory: 'Test Automation',
          manualDays: 12,
          aiDays: 8,
          toolMonthlyCost: 0,
          confidence: 'Medium',
          rationale: 'The 53-class surface area is the main risk — Copado AI auto-generates regression tests from existing code',
        },
        {
          phase: 'Deployment',
          task: 'Release pipeline + quality gate rules',
          description: 'Configure Copado pipeline stages with automated quality gate enforcement',
          aiTool: 'Copado',
          aiToolCategory: 'Deployment',
          manualDays: 5,
          aiDays: 3,
          toolMonthlyCost: 156,
          confidence: 'High',
          rationale: 'Copado native integration; no custom webhook work needed',
        },
        {
          phase: 'Docs',
          task: 'Generate developer runbook',
          description: 'Auto-generate usage guide, rule catalogue, and override process docs',
          aiTool: 'Claude',
          aiToolCategory: 'Docs',
          manualDays: 3,
          aiDays: 2,
          toolMonthlyCost: 0,
          confidence: 'High',
          rationale: 'Claude produces draft runbook from codebase context in under an hour',
        },
      ],
      toolchain: [
        { layer: 'Code analysis', tool: 'PMD + Einstein Code', purpose: 'Apex static analysis with custom rulesets', monthlyCost: 0, alternatives: 'Checkmarx, SonarQube' },
        { layer: 'CI/CD', tool: 'Copado', purpose: 'Pipeline orchestration and quality gate enforcement', monthlyCost: 156, alternatives: 'GitHub Actions only' },
        { layer: 'LLM', tool: 'Claude', purpose: 'Requirements drafting and runbook generation', monthlyCost: 19, alternatives: 'GPT-4o' },
        { layer: 'Code assistance', tool: 'GitHub Copilot', purpose: 'Pipeline YAML and config authoring', monthlyCost: 0, alternatives: 'Cursor, Einstein Code' },
      ],
      risks: [
        'Regression risk against 53 existing Apex classes — false-positive rate needs tuning before go-live',
        '5 Aura components may use non-standard patterns that trigger rule violations; needs exclusion list',
      ],
      architectureNotes: [
        'Existing Aura components should be excluded from LWC linting rules until an Aura-to-LWC migration is planned',
        'PMD custom ruleset should be seeded from the existing 53 classes to avoid flagging established patterns as violations',
      ],
    },
    {
      optionLabel: 'Fastest time-to-market',
      optimizedFor: 'Production in 4 weeks using maximum AI parallelism',
      tradeoff: 'Higher tooling cost; some tasks run in parallel requiring more coordination',
      title: 'Apex Quality Gate — Accelerated',
      summary: 'Full parallel delivery using Cursor for rapid Apex engine build and Mabl for automated test generation. Reaches production in 4 weeks by running design and development concurrently.',
      complexity: 'High',
      totalManualDays: 45,
      totalAiDays: 18,
      totalManualCost: 32400,
      totalAiCost: 14600,
      monthlyRunCost: 510,
      deployTimeWeeks: 4,
      aiTimeSavingPct: 60,
      banner: 'AI delivers the bot in 4 weeks vs 9 — 60% faster — by parallelising design and development with Cursor and Einstein Code.',
      tasks: [
        {
          phase: 'Requirements',
          task: 'AI-generated quality ruleset from codebase',
          description: 'Claude analyses existing 53 Apex classes and auto-proposes quality rules',
          aiTool: 'Claude',
          aiToolCategory: 'Requirements',
          manualDays: 4,
          aiDays: 1,
          toolMonthlyCost: 0,
          confidence: 'High',
          rationale: 'Claude can ingest the full Apex codebase and propose ruleset in a single session — 75% faster than manual workshops',
        },
        {
          phase: 'Design',
          task: 'Architect integration layer (parallel with dev)',
          description: 'AI-assisted architecture for GitHub Actions webhook and Copado quality gate API',
          aiTool: 'GitHub Copilot',
          aiToolCategory: 'Code Gen',
          manualDays: 5,
          aiDays: 2,
          toolMonthlyCost: 19,
          confidence: 'High',
          rationale: 'Copilot generates integration boilerplate; runs parallel to development sprint',
        },
        {
          phase: 'Development',
          task: 'Build analysis engine with Cursor',
          description: 'Full Apex AST parser and rule engine built using AI pair-programming',
          aiTool: 'Cursor',
          aiToolCategory: 'Code Gen',
          manualDays: 16,
          aiDays: 8,
          toolMonthlyCost: 40,
          confidence: 'Medium',
          rationale: 'Outside selected stack — Cursor is ~2x faster than Copilot for complex Apex engine work at $40/mo',
        },
        {
          phase: 'Testing / QA',
          task: 'AI-generated test suite for 53 Apex classes',
          description: 'Automated regression and edge-case generation using Mabl AI',
          aiTool: 'Mabl',
          aiToolCategory: 'Test Automation',
          manualDays: 12,
          aiDays: 4,
          toolMonthlyCost: 200,
          confidence: 'Medium',
          rationale: 'Outside selected stack — Mabl auto-generates tests from Apex class signatures, cutting QA from 12 to 4 days',
        },
        {
          phase: 'Deployment',
          task: 'Automated pipeline deployment',
          description: 'One-click Copado deployment with quality gate pre-configured',
          aiTool: 'Copado',
          aiToolCategory: 'Deployment',
          manualDays: 5,
          aiDays: 2,
          toolMonthlyCost: 156,
          confidence: 'High',
          rationale: 'Copado native; no custom config needed beyond threshold values',
        },
        {
          phase: 'Docs',
          task: 'Auto-generate full documentation suite',
          description: 'Runbook, rule catalogue, and onboarding guide generated from code',
          aiTool: 'Claude',
          aiToolCategory: 'Docs',
          manualDays: 3,
          aiDays: 1,
          toolMonthlyCost: 0,
          confidence: 'High',
          rationale: 'Claude produces production-ready docs from codebase in under 2 hours',
        },
      ],
      toolchain: [
        { layer: 'Code analysis', tool: 'Cursor + PMD', purpose: 'Rapid Apex engine development and rule execution', monthlyCost: 40, alternatives: 'Einstein Code, GitHub Copilot' },
        { layer: 'Test automation', tool: 'Mabl AI', purpose: 'Automated regression test generation for 53 Apex classes', monthlyCost: 200, alternatives: 'Copado AI, manual' },
        { layer: 'CI/CD', tool: 'Copado', purpose: 'Pipeline and quality gate enforcement', monthlyCost: 156, alternatives: 'GitHub Actions' },
        { layer: 'LLM', tool: 'Claude', purpose: 'Requirements generation and documentation', monthlyCost: 114, alternatives: 'GPT-4o' },
      ],
      risks: [
        'Parallel design/dev tracks require tight sync — scope creep likely without a dedicated tech lead',
        'Mabl is outside the current tool stack — procurement and onboarding adds 3–5 days if not already approved',
      ],
      architectureNotes: [
        'Parallel sprints only work if the integration API contract is locked on day 2 — any change breaks both tracks',
        'The 5 Aura components create a coexistence risk with LWC linting; recommend an exclusion config from day 1',
      ],
    },
    {
      optionLabel: 'Balanced',
      optimizedFor: 'Best overall value — strong AI savings without over-tooling',
      tradeoff: 'Moderate cost and timeline; uses only tools already in the Salesforce stack',
      title: 'Apex Quality Gate — Recommended',
      summary: 'Delivers the bot in 6 weeks using Einstein Code and Copado AI already licensed in the org. Balances AI acceleration against the regression risk from 53 existing Apex classes with a dedicated testing sprint.',
      complexity: 'Medium',
      totalManualDays: 45,
      totalAiDays: 23,
      totalManualCost: 32400,
      totalAiCost: 10900,
      monthlyRunCost: 330,
      deployTimeWeeks: 6,
      aiTimeSavingPct: 49,
      banner: 'AI saves 22 delivery days (49% faster) using tools already licensed in the org — no new procurement needed.',
      tasks: [
        {
          phase: 'Requirements',
          task: 'Define quality rules from existing codebase',
          description: 'Claude analyses 53 Apex classes to propose quality thresholds and security rules',
          aiTool: 'Claude',
          aiToolCategory: 'Requirements',
          manualDays: 4,
          aiDays: 2,
          toolMonthlyCost: 0,
          confidence: 'High',
          rationale: 'Claude ingests the full Apex codebase and proposes a calibrated ruleset — 2 days vs 4 for manual workshops',
        },
        {
          phase: 'Design',
          task: 'Design GitHub Actions + Copado pipeline',
          description: 'Architecture for PR-triggered analysis with quality gate blocking deployments',
          aiTool: 'GitHub Copilot',
          aiToolCategory: 'Code Gen',
          manualDays: 5,
          aiDays: 3,
          toolMonthlyCost: 19,
          confidence: 'High',
          rationale: 'Copilot generates pipeline YAML and webhook handlers; established integration pattern for Copado',
        },
        {
          phase: 'Development',
          task: 'Build Apex analysis engine + LWC rule parser',
          description: 'Custom PMD rules + parser for LWC and Apex with existing codebase as training context',
          aiTool: 'Einstein Code',
          aiToolCategory: 'Code Gen',
          manualDays: 15,
          aiDays: 8,
          toolMonthlyCost: 0,
          confidence: 'Medium',
          rationale: 'Already licensed — $0. Einstein Code trained on Salesforce patterns; particularly effective for the 53-class context',
        },
        {
          phase: 'Testing / QA',
          task: 'Regression suite against 53 Apex classes + Aura',
          description: 'Full regression ensuring bot does not flag existing compliant code as violations',
          aiTool: 'Copado AI',
          aiToolCategory: 'Test Automation',
          manualDays: 12,
          aiDays: 6,
          toolMonthlyCost: 0,
          confidence: 'Medium',
          rationale: 'Already licensed — $0. The 53-class + 5-Aura surface area is the highest risk; dedicated sprint recommended',
        },
        {
          phase: 'Deployment',
          task: 'Copado pipeline with quality gate config',
          description: 'Configure multi-stage Copado pipeline with threshold-based deployment blocking',
          aiTool: 'Copado',
          aiToolCategory: 'Deployment',
          manualDays: 5,
          aiDays: 3,
          toolMonthlyCost: 156,
          confidence: 'High',
          rationale: 'Native Copado integration; quality gate API is well-documented',
        },
        {
          phase: 'Docs',
          task: 'Generate runbook and onboarding guide',
          description: 'Developer runbook, rule override process, and team onboarding documentation',
          aiTool: 'Claude',
          aiToolCategory: 'Docs',
          manualDays: 4,
          aiDays: 1,
          toolMonthlyCost: 0,
          confidence: 'High',
          rationale: 'Claude generates production-ready documentation from codebase context in under 2 hours',
        },
      ],
      toolchain: [
        { layer: 'Code analysis', tool: 'PMD + Einstein Code', purpose: 'Apex/LWC static analysis using org-native AI', monthlyCost: 0, alternatives: 'Checkmarx, SonarQube' },
        { layer: 'CI/CD + Testing', tool: 'Copado AI', purpose: 'Pipeline orchestration, quality gates, and AI test generation', monthlyCost: 156, alternatives: 'GitHub Actions + Mabl' },
        { layer: 'Code assistance', tool: 'GitHub Copilot', purpose: 'Pipeline config, YAML, and integration boilerplate', monthlyCost: 19, alternatives: 'Cursor, Einstein Code' },
        { layer: 'LLM', tool: 'Claude', purpose: 'Requirements synthesis and documentation generation', monthlyCost: 155, alternatives: 'GPT-4o, Gemini' },
      ],
      risks: [
        'Regression risk against 53 existing Apex classes is the primary delivery risk — budget 6 days for QA not 4',
        '5 legacy Aura components may need an exclusion list to avoid false-positive linting violations',
      ],
      architectureNotes: [
        'Existing Aura components should be scoped out of LWC lint rules until a formal Aura migration sprint is planned',
        'Seed the PMD custom ruleset from the existing 53 classes first — establishes a compliant baseline before adding new rules',
      ],
    },
  ],
};
